telescope:
  type: alpaca
  address: "127.0.0.1:11111"
  device_number: 0
  telescope_id: "T2"
  settle_time: 2.0    # settle time after each slewing operation


rotator:
  type: alpaca
  address: "127.0.0.1:11112"
  device_number: 0
  settle_time: 0.1
  mechanical_limits:
    min_deg: 94.0 #-126.0           # lowest possible state of running .MoveAbsolute() and becoming idle (instead of getting stuck)
    max_deg: 320.0 #100.0            # highest possible state of running .MoveAbsolute() and becoming idle (instead of getting stuck)
  initialization:
    strategy: "midpoint"      # "midpoint" will use (min_deg + max_deg)/2, use "safe_position" to utilize safe_position_deg
    safe_position_deg: 210    # if "safe_position" used as strategy, this will be where the rotator initalises its position to
  limits:
    warning_margin_deg: 3.0    # when to warn within limits (e.g. will warn limits approaching within N degrees of max/min)
    emergency_margin_deg: 1.0   # when to reject within limits (e.g. will reject moves within N degrees of max/min)
  

cover:
  type: alpaca
  address: "127.0.0.1:11112"
  device_number: 0
  operation_timeout: 30.0     # max timeout for open/close instructions
  settle_time: 15.0           # standard time to wait for covers to open and close


focuser:
  type: alpaca
  address: "127.0.0.1:11112"
  device_number: 0
  # Dict of optimal/starting focus positions for each filter
  focus_positions:          # starting focus positions for each filter (also used as starting points for t2_focus_sweep.py testing)
    l: 15120 # need to re-test
    b: 15100 # need to re-test
    g: 15110 # need to re-test
    r: 15130 # need to re-test
    c: 15040 # prev-15140
    i: 15120 # need to re-test
    h: 15140 # need to re-test
  focus_sweep:             # Only for use with t2_focus_sweep.py - for testing optimal filter/focuser positions
    range_steps: 40        # Â±N around starting pos
    step_size: 5           # test every N steps
    exposure_time: 5.0     # N seconds per image exposure time
    filters: ['C', 'L', 'B', 'G', 'R', 'I', 'H']  # which filters to test
  spectro_focus_position:
    spectro: 18800 # prev-18371 


filter_wheel:
  type: alpaca
  address: "127.0.0.1:11113"
  device_number: 0
  settle_time: 0.1        # time to wait after filter change


cameras:
  # main:                         
  #   type: alpaca
  #   address: "127.0.0.1:11113"      # can use this commented out code in place of the 6200MM code below, if the main photometry cam is out
  #   name_pattern: "294MM"
  #   role: 'guide'                
  #   default_binning: 4
  #   default_gain: 200
  #   target_temperature: -10.0
  main:                          
    type: alpaca
    address: "127.0.0.1:11113"  
    name_pattern: "6200MM"
    role: 'main'                 
    default_binning: 4
    default_gain: 100
    target_temperature: -15.0
  guide:                         
    type: alpaca
    address: "127.0.0.1:11113"  
    name_pattern: "294MM"
    role: 'guide'                
    default_binning: 4
    default_gain: 200     # upped this to 200
    target_temperature: -10.0
    
  

  