telescope:
  type: alpaca
  address: "127.0.0.1:11111"
  device_number: 0
  telescope_id: "T2"
  settle_time: 2.0    # settle time after each slewing operation

rotator:
  type: alpaca
  address: "127.0.0.1:11112"
  device_number: 0
  settle_time: 0.1
  mechanical_limits:
    min_deg: 94.0 #-126.0           # lowest possible state of .MoveAbsolute() and becoming idle
    max_deg: 320.0 #100.0            # highest possible state of .MoveAbsolute() and becoming idle
  initialization:
    strategy: "midpoint"      # "midpoint" will use (min_deg + max_deg)/2, use "safe_position" to utilize safe_position_deg
    safe_position_deg: 220 #0.0
  limits:
    warning_margin_deg: 3.0    # when to warn within limits
    emergency_margin_deg: 1.0   # when to reject within limits
  

cover:
  type: alpaca
  address: "127.0.0.1:11112"
  device_number: 0
  operation_timeout: 30.0     # max timeout for open/close instructions
  settle_time: 15.0           # standard time to wait for covers to open and close

focuser:
  type: alpaca
  address: "127.0.0.1:11112"
  device_number: 0
  # maybe Dict of nominal values for Filters: Focus Lengths in here e.g.
  focus_positions:
    c: 15155
    l: 15200
    b: 14980
    g: 15050
    r: 15120
    i: 15180
    h: 15300
  focus_sweep:
    range_steps: 100        # Â±100 steps around optimal
    step_size: 10           # test every 10 steps
    exposure_time: 3.0      # 3 seconds per image
    filters: ['C', 'L', 'B', 'G', 'R', 'I', 'H']  # which to test
  spectro_focus_position:
    spectro: 18433 #?



filter_wheel:
  type: alpaca
  address: "127.0.0.1:11113"
  device_number: 0
  settle_time: 0.1        # time to wait after filter change

cameras:
  main:                         
    type: alpaca
    address: "127.0.0.1:11113"  
    name_pattern: "294MM"
    role: 'guide'                
    default_binning: 4
    default_gain: 150
    target_temperature: -10.0
  # main:                          
  #   type: alpaca
  #   address: "127.0.0.1:11113"  
  #   name_pattern: "6200MM"
  #   role: 'main'                 
  #   default_binning: 4
  #   default_gain: 100
  #   target_temperature: -15.0
  
  guide:                         
    type: alpaca
    address: "127.0.0.1:11113"  
    name_pattern: "294MM"
    role: 'guide'                
    default_binning: 4
    default_gain: 150
    target_temperature: -10.0
    
  


  
