latitude: -27.7983683
longitude: 151.8547855
altitude: 680.0
timezone: "Australia/Brisbane"

min_altitude: 30.0      # Minimum altitude for a target to be observable
twilight_altitude: -9.0 # Required altitude for the Sun (at Sunset and Sunrise) for observations and imaging to be allowed

#dome_closure_statuses: ['weather_danger_closing', 'closing_both_panels', 'close_requested_left',
# 'close_requested_right', 'close_requested', 'closed']