raw_images: "P:\\Photometry"                  # Spectro guide cam images go here, too??? P:\\Spectro ??
spectro_images: "P:\\Spectroscopy"
logs: "P:\\temp\\logs"

target_json: "P:\\temp\\target_2.json"              # For minerva photometry to read target info
solver_status_json : "session\\solver_status_json"

platesolve_json: "P:\\temp\\wcssolution_2.json"     # Where minerva photometry dumps mount correction info
spectro_platesolve_json: "P:\\temp\\wcssolution_2.json"  # will this be same for spectro??